# Generated by Django 6.0.3 on 2026-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
