# Generated by Django 6.0.3 on 2026-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_set_existing_users_first_time_login_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='driver_status',
            field=models.CharField(choices=[('available', 'Available'), ('in_trip', 'In Trip'), ('clocked_out', 'Clocked Out')], default='clocked_out', max_length=20),
        ),
    ]
