# Generated by Django 6.0.3 on 2026-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_rest_leave_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='driver_status',
            field=models.CharField(choices=[('available', 'Available'), ('in_trip', 'In Trip'), ('clocked_out', 'Clocked Out'), ('on_rest', 'On Rest'), ('on_leave', 'On Leave')], default='clocked_out', max_length=20),
        ),
    ]
