# Generated by Django 6.0 on 2026-03-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_checklists',
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('sequence_no', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inspection_checklist_items',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'inspection_results',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=30)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_trip', 'In Trip'), ('idle', 'Idle'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('current_mileage_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_service_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('in_repair', 'In Repair'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_issues',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('pre_trip', 'Pre-Trip'), ('post_trip', 'Post-Trip'), ('ad_hoc', 'Ad-Hoc')], default='pre_trip', max_length=20)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspections',
            },
        ),
    ]
