# Generated by Django 6.0 on 2026-03-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='fleet.inspectionchecklist'),
        ),
        migrations.AddField(
            model_name='inspectionchecklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fleet.inspectionchecklist'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fleet.inspectionchecklistitem'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fleet.inspection'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='fleet.inspection'),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='fleet.vehicle'),
        ),
    ]
