# Generated by Django 6.0.3 on 2026-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_inspection_assigned_to_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
