# Generated by Django 6.0.3 on 2026-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehicle_status_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='overall_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('maintenance_scheduled', 'Maintenance Scheduled')], default='pending', max_length=30),
        ),
    ]
