# Generated by Django 6.0.3 on 2026-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(choices=[('sos', 'SOS'), ('route_deviation', 'Route Deviation'), ('geofence_entry', 'Geofence Entry'), ('geofence_exit', 'Geofence Exit'), ('maintenance_due', 'Maintenance Due'), ('issue_reported', 'Issue Reported'), ('trip_rejected', 'Trip Rejected'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_request', 'Leave Request')], max_length=20),
        ),
    ]
