# Generated by Django 6.0.3 on 2026-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_sparepart_fix_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'verbose_name': 'Spare Part'},
        ),
    ]
