# Generated by Django 6.0.3 on 2026-03-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_sparepart_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE maintenance_records ALTER COLUMN parts_used DROP NOT NULL;",
            reverse_sql="ALTER TABLE maintenance_records ALTER COLUMN parts_used SET NOT NULL;",
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='parts_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
