# Generated by Django 6.0.3 on 2026-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_sparepart_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='maintenancerecord',
                    name='parts_used',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
            database_operations=[],  # Column already exists in the database
        ),
    ]
